### ISSUE TITLE
Need IT Help

### ISSUE THREAD

**Issue by georgiamoon** [newamericafoundation/IT-Web-Management#2]
I'm having issues with my computer and my mouse doesn't have batteries.

Also in two weeks i have a new hire starting, I need accounts for them and a computer.

- Program Director

**Comment by georgiamoon** [comment]
Happy to help!

I'm going to create multiple tickets for this so that we can track each item.

- [ ] Computer /mouse stuff #3
- [ ] New hire accounts #4
- [ ] New hire computer #5
